package router

import (
	"encoding/json"
	"net/http"

	"github.com/0xstxrless/punkt/backend/internal/db"
	"github.com/go-chi/chi/v5"
)

// only images url aren't sanitized, since they are generated by the backend and not user input
func (h *App) CreatePin(w http.ResponseWriter, r *http.Request) {
	var params db.CreatePinParams
	if err := json.NewDecoder(r.Body).Decode(&params); err != nil {
		h.logError("Invalid pin parameters", w, r, http.StatusBadRequest, err)
		return
	}

	var err error
	params.Title, err = h.sanitize(params.Title, CHARLIMIT)
	if err != nil {
		h.logError("Invalid param title", w, r, http.StatusBadRequest, err)
		return
	}

	params.Category, err = h.sanitize(params.Category, CHARLIMIT)
	if err != nil {
		h.logError("Invalid param category", w, r, http.StatusBadRequest, err)
		return
	}

	if params.Lat < -90 || params.Lat > 90 {
		h.logError("Invalid latitude", w, r, http.StatusBadRequest, nil)
		return
	}
	if params.Lng < -180 || params.Lng > 180 {
		h.logError("Invalid longitude", w, r, http.StatusBadRequest, nil)
		return
	}

	pin, err := h.Queries.CreatePin(r.Context(), params)
	if err != nil {
		h.logError("Couldn't create pin", w, r, http.StatusBadRequest, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(pin)
}

func (h *App) GetPins(w http.ResponseWriter, r *http.Request) {
	pins, err := h.Queries.ListPins(r.Context())
	if err != nil {
		h.logError("Error fetching pins:", w, r, http.StatusInternalServerError, err)
		return
	}
	h.logError("Fetched pins:", w, r, http.StatusOK, nil)
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(pins)
}

func (h *App) GetPin(w http.ResponseWriter, r *http.Request) {
	pinID, err := h.paramIDtoInt(r)
	if err != nil {
		h.logError("Invalid pin ID", w, r, http.StatusNotFound, err)
		return
	}

	pin, err := h.Queries.GetPin(r.Context(), int32(pinID))
	if err != nil {
		h.logError("Error fetching pin %d: %v\n", w, r, pinID, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(pin)
}

func (h *App) UpdatePin(w http.ResponseWriter, r *http.Request) {
	pinID, err := h.paramIDtoInt(r)
	if err != nil {
		h.logError("Invalid pin ID", w, r, http.StatusNotFound, err)
		return
	}

	var params db.UpdatePinParams
	params.ID = int32(pinID)

	if err := json.NewDecoder(r.Body).Decode(&params); err != nil {
		h.logError("Invalid request body", w,r, http.StatusBadRequest, err)
		return
	}

	pin, err := h.Queries.UpdatePin(r.Context(), params)
	if err != nil {
		h.logError("Error updating pin %d: %v\n", w, r, pinID, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(pin)
}

func (h *App) DeletePin(w http.ResponseWriter, r *http.Request) {
	pinID, err := h.paramIDtoInt(r)
	if err != nil {
		h.logError("Invalid pin ID", w, r, http.StatusNotFound, err)
		return
	}

	if err := h.Queries.DeletePin(r.Context(), int32(pinID)); err != nil {
		h.logError("Pin Couldn't be deleted", w, r, http.StatusBadRequest, err)
		return
	}
}

func (h *App) ListPinsByCategory(w http.ResponseWriter, r *http.Request) {
	category, err := h.sanitize(chi.URLParam(r, "category"), CHARLIMIT)
	if err != nil {
		h.logError("Invalid category name", w, r, http.StatusBadRequest, err)
		return
	}

	pins, err := h.Queries.ListPinsByCategory(r.Context(), category)
	if err != nil {
		h.logError("Couldn't fetch pins by category", w, r, http.StatusInternalServerError, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(pins)
}
