// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUpdate struct {
	ID          int32              `db:"id" json:"id"`
	Version     string             `db:"version" json:"version"`
	Title       string             `db:"title" json:"title"`
	Description string             `db:"description" json:"description"`
	Features    string             `db:"features" json:"features"`
	ReleasedAt  pgtype.Timestamptz `db:"released_at" json:"released_at"`
}

type Category struct {
	Name  string `db:"name" json:"name"`
	Color string `db:"color" json:"color"`
}

type PatrolPlan struct {
	ID        int32              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Date      string             `db:"date" json:"date"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PatrolPlanPin struct {
	ID           int32              `db:"id" json:"id"`
	PatrolPlanID int32              `db:"patrol_plan_id" json:"patrol_plan_id"`
	PinID        int32              `db:"pin_id" json:"pin_id"`
	SortOrder    int32              `db:"sort_order" json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Pin struct {
	ID          int32              `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Description pgtype.Text        `db:"description" json:"description"`
	Lat         float64            `db:"lat" json:"lat"`
	Lng         float64            `db:"lng" json:"lng"`
	Category    string             `db:"category" json:"category"`
	ImageUrl    pgtype.Text        `db:"image_url" json:"image_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version     int32              `db:"version" json:"version"`
	VisitsCount pgtype.Int4        `db:"visits_count" json:"visits_count"`
}

type StreetworkStat struct {
	ID            int32              `db:"id" json:"id"`
	WorkerName    string             `db:"worker_name" json:"worker_name"`
	Month         string             `db:"month" json:"month"`
	Interactions  int32              `db:"interactions" json:"interactions"`
	NewContacts   int32              `db:"new_contacts" json:"new_contacts"`
	Interventions int32              `db:"interventions" json:"interventions"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Avatar        pgtype.Text        `db:"avatar" json:"avatar"`
	BgColor       pgtype.Text        `db:"bg_color" json:"bg_color"`
}

type User struct {
	ID                 int32              `db:"id" json:"id"`
	Email              string             `db:"email" json:"email"`
	PasswordHash       string             `db:"password_hash" json:"password_hash"`
	MustChangePassword pgtype.Bool        `db:"must_change_password" json:"must_change_password"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastLogin          pgtype.Timestamptz `db:"last_login" json:"last_login"`
}

type UserUpdatesViewed struct {
	ID       int32              `db:"id" json:"id"`
	UserID   int32              `db:"user_id" json:"user_id"`
	UpdateID int32              `db:"update_id" json:"update_id"`
	ViewedAt pgtype.Timestamptz `db:"viewed_at" json:"viewed_at"`
}

type Visit struct {
	ID        int32              `db:"id" json:"id"`
	PinID     int32              `db:"pin_id" json:"pin_id"`
	Name      string             `db:"name" json:"name"`
	Note      pgtype.Text        `db:"note" json:"note"`
	ImageUrl  pgtype.Text        `db:"image_url" json:"image_url"`
	VisitedAt pgtype.Timestamptz `db:"visited_at" json:"visited_at"`
}
