// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPinToPatrolPlan = `-- name: AddPinToPatrolPlan :one
INSERT INTO patrol_plan_pins (patrol_plan_id, pin_id, sort_order)
VALUES ($1, $2, $3)
RETURNING id, patrol_plan_id, pin_id, sort_order, created_at
`

type AddPinToPatrolPlanParams struct {
	PatrolPlanID int32 `db:"patrol_plan_id" json:"patrol_plan_id"`
	PinID        int32 `db:"pin_id" json:"pin_id"`
	SortOrder    int32 `db:"sort_order" json:"sort_order"`
}

func (q *Queries) AddPinToPatrolPlan(ctx context.Context, arg AddPinToPatrolPlanParams) (PatrolPlanPin, error) {
	row := q.db.QueryRow(ctx, addPinToPatrolPlan, arg.PatrolPlanID, arg.PinID, arg.SortOrder)
	var i PatrolPlanPin
	err := row.Scan(
		&i.ID,
		&i.PatrolPlanID,
		&i.PinID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, color) VALUES ($1, $2) RETURNING name, color
`

type CreateCategoryParams struct {
	Name  string `db:"name" json:"name"`
	Color string `db:"color" json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Color)
	var i Category
	err := row.Scan(&i.Name, &i.Color)
	return i, err
}

const createPatrolPlan = `-- name: CreatePatrolPlan :one
INSERT INTO patrol_plans (name, date)
VALUES ($1, $2)
RETURNING id, name, date, created_at, updated_at
`

type CreatePatrolPlanParams struct {
	Name string `db:"name" json:"name"`
	Date string `db:"date" json:"date"`
}

func (q *Queries) CreatePatrolPlan(ctx context.Context, arg CreatePatrolPlanParams) (PatrolPlan, error) {
	row := q.db.QueryRow(ctx, createPatrolPlan, arg.Name, arg.Date)
	var i PatrolPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPin = `-- name: CreatePin :one
INSERT INTO pins (title, description, lat, lng, category, image_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, lat, lng, category, image_url, created_at, updated_at, version, visits_count
`

type CreatePinParams struct {
	Title       string      `db:"title" json:"title"`
	Description pgtype.Text `db:"description" json:"description"`
	Lat         float64     `db:"lat" json:"lat"`
	Lng         float64     `db:"lng" json:"lng"`
	Category    string      `db:"category" json:"category"`
	ImageUrl    pgtype.Text `db:"image_url" json:"image_url"`
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) (Pin, error) {
	row := q.db.QueryRow(ctx, createPin,
		arg.Title,
		arg.Description,
		arg.Lat,
		arg.Lng,
		arg.Category,
		arg.ImageUrl,
	)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Lat,
		&i.Lng,
		&i.Category,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.VisitsCount,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, must_change_password, created_at, last_login
`

type CreateUserParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const createVisit = `-- name: CreateVisit :one
INSERT INTO visits (pin_id, name, note, image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, pin_id, name, note, image_url, visited_at
`

type CreateVisitParams struct {
	PinID    int32       `db:"pin_id" json:"pin_id"`
	Name     string      `db:"name" json:"name"`
	Note     pgtype.Text `db:"note" json:"note"`
	ImageUrl pgtype.Text `db:"image_url" json:"image_url"`
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (Visit, error) {
	row := q.db.QueryRow(ctx, createVisit,
		arg.PinID,
		arg.Name,
		arg.Note,
		arg.ImageUrl,
	)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.PinID,
		&i.Name,
		&i.Note,
		&i.ImageUrl,
		&i.VisitedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE name = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteCategory, name)
	return err
}

const deletePatrolPlan = `-- name: DeletePatrolPlan :exec
DELETE FROM patrol_plans WHERE id = $1
`

func (q *Queries) DeletePatrolPlan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePatrolPlan, id)
	return err
}

const deletePin = `-- name: DeletePin :exec
DELETE FROM pins WHERE id = $1
`

func (q *Queries) DeletePin(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePin, id)
	return err
}

const deleteVisit = `-- name: DeleteVisit :exec
DELETE FROM visits WHERE id = $1
`

func (q *Queries) DeleteVisit(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVisit, id)
	return err
}

const getLatestAppUpdate = `-- name: GetLatestAppUpdate :one
SELECT id, version, title, description, features, released_at FROM app_updates ORDER BY released_at DESC LIMIT 1
`

func (q *Queries) GetLatestAppUpdate(ctx context.Context) (AppUpdate, error) {
	row := q.db.QueryRow(ctx, getLatestAppUpdate)
	var i AppUpdate
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.Features,
		&i.ReleasedAt,
	)
	return i, err
}

const getPatrolPlan = `-- name: GetPatrolPlan :one

SELECT id, name, date, created_at, updated_at FROM patrol_plans WHERE id = $1
`

// queries/patrol_plans.sql
func (q *Queries) GetPatrolPlan(ctx context.Context, id int32) (PatrolPlan, error) {
	row := q.db.QueryRow(ctx, getPatrolPlan, id)
	var i PatrolPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatrolPlanWithPins = `-- name: GetPatrolPlanWithPins :many
SELECT
  ppp.sort_order,
  p.id, p.title, p.description, p.lat, p.lng, p.category, p.image_url, p.created_at, p.updated_at, p.version, p.visits_count
FROM patrol_plan_pins ppp
JOIN pins p ON p.id = ppp.pin_id
WHERE ppp.patrol_plan_id = $1
ORDER BY ppp.sort_order ASC
`

type GetPatrolPlanWithPinsRow struct {
	SortOrder   int32              `db:"sort_order" json:"sort_order"`
	ID          int32              `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Description pgtype.Text        `db:"description" json:"description"`
	Lat         float64            `db:"lat" json:"lat"`
	Lng         float64            `db:"lng" json:"lng"`
	Category    string             `db:"category" json:"category"`
	ImageUrl    pgtype.Text        `db:"image_url" json:"image_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version     int32              `db:"version" json:"version"`
	VisitsCount pgtype.Int4        `db:"visits_count" json:"visits_count"`
}

func (q *Queries) GetPatrolPlanWithPins(ctx context.Context, patrolPlanID int32) ([]GetPatrolPlanWithPinsRow, error) {
	rows, err := q.db.Query(ctx, getPatrolPlanWithPins, patrolPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPatrolPlanWithPinsRow
	for rows.Next() {
		var i GetPatrolPlanWithPinsRow
		if err := rows.Scan(
			&i.SortOrder,
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Lat,
			&i.Lng,
			&i.Category,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.VisitsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPin = `-- name: GetPin :one
SELECT id, title, description, lat, lng, category, image_url, created_at, updated_at, version, visits_count FROM pins WHERE id = $1
`

func (q *Queries) GetPin(ctx context.Context, id int32) (Pin, error) {
	row := q.db.QueryRow(ctx, getPin, id)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Lat,
		&i.Lng,
		&i.Category,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.VisitsCount,
	)
	return i, err
}

const getStatsByMonth = `-- name: GetStatsByMonth :many
SELECT id, worker_name, month, interactions, new_contacts, interventions, created_at, updated_at, avatar, bg_color FROM streetwork_stats WHERE month = $1 ORDER BY worker_name
`

func (q *Queries) GetStatsByMonth(ctx context.Context, month string) ([]StreetworkStat, error) {
	rows, err := q.db.Query(ctx, getStatsByMonth, month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreetworkStat
	for rows.Next() {
		var i StreetworkStat
		if err := rows.Scan(
			&i.ID,
			&i.WorkerName,
			&i.Month,
			&i.Interactions,
			&i.NewContacts,
			&i.Interventions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Avatar,
			&i.BgColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByWorker = `-- name: GetStatsByWorker :many

SELECT id, worker_name, month, interactions, new_contacts, interventions, created_at, updated_at, avatar, bg_color FROM streetwork_stats WHERE worker_name = $1 ORDER BY month DESC
`

// queries/streetwork_stats.sql
func (q *Queries) GetStatsByWorker(ctx context.Context, workerName string) ([]StreetworkStat, error) {
	rows, err := q.db.Query(ctx, getStatsByWorker, workerName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreetworkStat
	for rows.Next() {
		var i StreetworkStat
		if err := rows.Scan(
			&i.ID,
			&i.WorkerName,
			&i.Month,
			&i.Interactions,
			&i.NewContacts,
			&i.Interventions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Avatar,
			&i.BgColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnviewedUpdates = `-- name: GetUnviewedUpdates :many
SELECT au.id, au.version, au.title, au.description, au.features, au.released_at
FROM app_updates au
WHERE au.id NOT IN (
  SELECT update_id FROM user_updates_viewed WHERE user_id = $1
)
ORDER BY au.released_at DESC
`

func (q *Queries) GetUnviewedUpdates(ctx context.Context, userID int32) ([]AppUpdate, error) {
	rows, err := q.db.Query(ctx, getUnviewedUpdates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppUpdate
	for rows.Next() {
		var i AppUpdate
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.Features,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, email, password_hash, must_change_password, created_at, last_login FROM users WHERE email = $1
`

// queries/users.sql
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, must_change_password, created_at, last_login FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getVisitsByPin = `-- name: GetVisitsByPin :many

SELECT id, pin_id, name, note, image_url, visited_at FROM visits WHERE pin_id = $1 ORDER BY visited_at DESC
`

// queries/visits.sql
func (q *Queries) GetVisitsByPin(ctx context.Context, pinID int32) ([]Visit, error) {
	rows, err := q.db.Query(ctx, getVisitsByPin, pinID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visit
	for rows.Next() {
		var i Visit
		if err := rows.Scan(
			&i.ID,
			&i.PinID,
			&i.Name,
			&i.Note,
			&i.ImageUrl,
			&i.VisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPinVisits = `-- name: IncrementPinVisits :exec
UPDATE pins SET visits_count = COALESCE(visits_count, 0) + 1 WHERE id = $1
`

func (q *Queries) IncrementPinVisits(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementPinVisits, id)
	return err
}

const listAppUpdates = `-- name: ListAppUpdates :many

SELECT id, version, title, description, features, released_at FROM app_updates ORDER BY released_at DESC
`

// queries/app_updates.sql
func (q *Queries) ListAppUpdates(ctx context.Context) ([]AppUpdate, error) {
	rows, err := q.db.Query(ctx, listAppUpdates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppUpdate
	for rows.Next() {
		var i AppUpdate
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.Features,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many

SELECT name, color FROM categories ORDER BY name
`

// queries/categories.sql
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatrolPlans = `-- name: ListPatrolPlans :many
SELECT id, name, date, created_at, updated_at FROM patrol_plans ORDER BY created_at DESC
`

func (q *Queries) ListPatrolPlans(ctx context.Context) ([]PatrolPlan, error) {
	rows, err := q.db.Query(ctx, listPatrolPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatrolPlan
	for rows.Next() {
		var i PatrolPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPins = `-- name: ListPins :many
SELECT id, title, description, lat, lng, category, image_url, created_at, updated_at, version, visits_count FROM pins ORDER BY created_at DESC
`

func (q *Queries) ListPins(ctx context.Context) ([]Pin, error) {
	rows, err := q.db.Query(ctx, listPins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pin
	for rows.Next() {
		var i Pin
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Lat,
			&i.Lng,
			&i.Category,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.VisitsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinsByCategory = `-- name: ListPinsByCategory :many
SELECT id, title, description, lat, lng, category, image_url, created_at, updated_at, version, visits_count FROM pins WHERE category = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPinsByCategory(ctx context.Context, category string) ([]Pin, error) {
	rows, err := q.db.Query(ctx, listPinsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pin
	for rows.Next() {
		var i Pin
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Lat,
			&i.Lng,
			&i.Category,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.VisitsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUpdateViewed = `-- name: MarkUpdateViewed :one
INSERT INTO user_updates_viewed (user_id, update_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING id, user_id, update_id, viewed_at
`

type MarkUpdateViewedParams struct {
	UserID   int32 `db:"user_id" json:"user_id"`
	UpdateID int32 `db:"update_id" json:"update_id"`
}

func (q *Queries) MarkUpdateViewed(ctx context.Context, arg MarkUpdateViewedParams) (UserUpdatesViewed, error) {
	row := q.db.QueryRow(ctx, markUpdateViewed, arg.UserID, arg.UpdateID)
	var i UserUpdatesViewed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UpdateID,
		&i.ViewedAt,
	)
	return i, err
}

const removePinFromPatrolPlan = `-- name: RemovePinFromPatrolPlan :exec
DELETE FROM patrol_plan_pins WHERE patrol_plan_id = $1 AND pin_id = $2
`

type RemovePinFromPatrolPlanParams struct {
	PatrolPlanID int32 `db:"patrol_plan_id" json:"patrol_plan_id"`
	PinID        int32 `db:"pin_id" json:"pin_id"`
}

func (q *Queries) RemovePinFromPatrolPlan(ctx context.Context, arg RemovePinFromPatrolPlanParams) error {
	_, err := q.db.Exec(ctx, removePinFromPatrolPlan, arg.PatrolPlanID, arg.PinID)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users
SET password_hash = $2, must_change_password = false
WHERE id = $1
`

type SetPasswordHashParams struct {
	ID           int32  `db:"id" json:"id"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories 
SET color = $2 
WHERE name = $1 
RETURNING name, color
`

type UpdateCategoryParams struct {
	Name  string `db:"name" json:"name"`
	Color string `db:"color" json:"color"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.Color)
	var i Category
	err := row.Scan(&i.Name, &i.Color)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login = now() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updatePin = `-- name: UpdatePin :one
UPDATE pins
SET title = $2, description = $3, lat = $4, lng = $5,
    category = $6, image_url = $7, updated_at = now(), version = version + 1
WHERE id = $1
RETURNING id, title, description, lat, lng, category, image_url, created_at, updated_at, version, visits_count
`

type UpdatePinParams struct {
	ID          int32       `db:"id" json:"id"`
	Title       string      `db:"title" json:"title"`
	Description pgtype.Text `db:"description" json:"description"`
	Lat         float64     `db:"lat" json:"lat"`
	Lng         float64     `db:"lng" json:"lng"`
	Category    string      `db:"category" json:"category"`
	ImageUrl    pgtype.Text `db:"image_url" json:"image_url"`
}

func (q *Queries) UpdatePin(ctx context.Context, arg UpdatePinParams) (Pin, error) {
	row := q.db.QueryRow(ctx, updatePin,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Lat,
		arg.Lng,
		arg.Category,
		arg.ImageUrl,
	)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Lat,
		&i.Lng,
		&i.Category,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.VisitsCount,
	)
	return i, err
}

const updateVisit = `-- name: UpdateVisit :one
UPDATE visits
SET name = $2,
    note = $3,
    image_url = $4,
    pin_id = $5
WHERE id = $1
RETURNING id, pin_id, name, note, image_url, visited_at
`

type UpdateVisitParams struct {
	ID       int32       `db:"id" json:"id"`
	Name     string      `db:"name" json:"name"`
	Note     pgtype.Text `db:"note" json:"note"`
	ImageUrl pgtype.Text `db:"image_url" json:"image_url"`
	PinID    int32       `db:"pin_id" json:"pin_id"`
}

func (q *Queries) UpdateVisit(ctx context.Context, arg UpdateVisitParams) (Visit, error) {
	row := q.db.QueryRow(ctx, updateVisit,
		arg.ID,
		arg.Name,
		arg.Note,
		arg.ImageUrl,
		arg.PinID,
	)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.PinID,
		&i.Name,
		&i.Note,
		&i.ImageUrl,
		&i.VisitedAt,
	)
	return i, err
}

const upsertStreetworkStat = `-- name: UpsertStreetworkStat :one
INSERT INTO streetwork_stats (worker_name, month, interactions, new_contacts, interventions)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (worker_name, month) DO UPDATE
SET interactions = $3, new_contacts = $4, interventions = $5, updated_at = now()
RETURNING id, worker_name, month, interactions, new_contacts, interventions, created_at, updated_at, avatar, bg_color
`

type UpsertStreetworkStatParams struct {
	WorkerName    string `db:"worker_name" json:"worker_name"`
	Month         string `db:"month" json:"month"`
	Interactions  int32  `db:"interactions" json:"interactions"`
	NewContacts   int32  `db:"new_contacts" json:"new_contacts"`
	Interventions int32  `db:"interventions" json:"interventions"`
}

func (q *Queries) UpsertStreetworkStat(ctx context.Context, arg UpsertStreetworkStatParams) (StreetworkStat, error) {
	row := q.db.QueryRow(ctx, upsertStreetworkStat,
		arg.WorkerName,
		arg.Month,
		arg.Interactions,
		arg.NewContacts,
		arg.Interventions,
	)
	var i StreetworkStat
	err := row.Scan(
		&i.ID,
		&i.WorkerName,
		&i.Month,
		&i.Interactions,
		&i.NewContacts,
		&i.Interventions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.BgColor,
	)
	return i, err
}
